### ISSUE TITLE
RWD 縮放問題

### ISSUE THREAD

**Issue by KevinYang0120** [okaoka0709/snow-calendar#1]
Hi, 

在demo的功能操作看起來都很好, 但我嘗試套用在Quasar Framework下, 發現只有在width:768~992正常
是否我這邊需另外調整?

![question](https://user-images.githubusercontent.com/30248187/52051153-a4fa6300-258d-11e9-9d45-c11a5c045d4a.gif)

**Comment by okaoka0709** [comment]
![演示動畫](https://lh3.googleusercontent.com/1UqRLqfBY9T0PO4o_R56rZf75SaMDNi_Z8bpf6OIZDQBNZESTTkIlorstOYsQKCxkTlgpsqO9AJ9Y-RERWZ5l5llCsmINjVAL8bd1V_l5eHmQi6pkE7SKf0yyBECtmobyctdQM2dQlDdHvVmLQQzWR1hcVancdThjV0HdbR-RV8LOvBzU5Q_vz8l7ZGUaziD6h3l73bJmeKfS71wwyRgXvqGUQ2iiUMLg9eGop-rBIJZ18arFp6HUuEFi6m6t_7GONz_EC5fvYQsJGcj9Ao4LKgBHfVuhlYZSjeZfSuYe8TXPjxF8teFZfSd0pe5_7AIex9y1RB0UeZLnNps97xQ8wC2aYL9RklTut4byjonX7ddUxKUAGsEWCtjyUpznPqKexEa-h2U-mrI5PV1k7vEKdwFhWwSCKMAJuaFdWVew6dvM8u3SXh0PAGIubeZRkopVCRgOPCBFObLQwIYhr8ccRQNhZGsXn7mGBQUGoLgXMYZ65WTx2Rqg6wp1xVb9LoVUo_510qrsLc0tnYGyeaMMiZy9rTiWZSRyM2Q9xEGT9Y6HI_NsF2_Pkn-Y541qBQCto6_JGUd12AsSB6QlssAewL5giag1mjW=w2242-h1058)

檢查之後發現是 Quasar 裡面的 quasar.mat.styl.css 對 class .md 做了一些事，跟我的命名重覆了(尤其還加上 !important)。

建議你可以覆寫他: 
```
.g.article-layout .md {
    display: block !important;
}
```

![桌機版消失的部分](https://lh3.googleusercontent.com/ddd72hVUuKwtX15tCCIW_tRj_aix7SowTDRfPHSZeKBTgmUOQF7VTQ_mmUKLQrcwbU3ecoBZt3Fodnj60Ch48MH0XqqsBb1JmU2zHXv_SRcMtLdJmCVMlRwGj5X6wMP_ZexuU80jvsrP-AycJSo-cZmHmbhB5QH2GjjvdCmQklAewno6miCrfdKiFcEpKds-f6D4ljFYRPZbHK7vXhX--ecU6wrMZJhRNkY509ZDkGIQvzFwL4PwpCsHmZ5wPuXDdsIHpgybApTn7IGkXH0Q-qS0c6Ltb9b7C9jgIQ0GpIzenXtTI_Zlu2r0C2tppVYycm709A70rZIsnPMIgv4cSWTvUjPi5TTGFbD0nfcZDemkDaiecGx4Ur8jFjSl3dYVJu6OBzV1GQFR86DOvn1y1hU2pwimoCYfUYwoQ35Gk95fLJumJvzQWHIzSMqO2sKPUMbCxiqo7FKqLezEnW8L3YRIa23R7mU1VmDxj18lWUQoOCJpiuVUwgY_2XD2CQOAKRwweatAmx27oEJ7CETBwpqsLfu5_ntyr3b94NkycjP98bukQ6Gh6fFyPO6Lo_K5Z_nHSf_1vLLldlrIf8Rm6wJ9_xDpBzF9f1aDMk8=w2560-h1380)

![手機版消失的部分](https://lh3.googleusercontent.com/pGxYQ-25suhi9pzwXL9KBDmODZnpP6khWt7lLBuxjKMay5d2AQpPkW9cCbAhKW2dEBKiykOJYa_bBRUmeqAQbHXPVNJhE1bqA4fzPoVyzxcIV6L4ke17wO5NG5IKl7-A29AlLZZkkJZDQrY87XFnNt6GntStu1DegM0DYdXlUS9KGzppa_e6QOL5y9h2zFEFcKgSgSnfaatLfO0I3XgJqbdhnFctGMRYLt2JCYPsU0mFZmlaNur7KWL-z2ZO9W_I2K_iXrpImc3oxmeSNo0EKVoV9VZTWp8xIvr81D8YvcpDhncTrFsOriNByF83rT6EgPN05u7yi7IAHLfLvKe8M_8XduszSfEpphNfYZjE3dNoTDEgSTNa-fbd_z3OQ6o0xQmuVYXxAAZSm21QKcHbYlPpnWu5oeee7r4yrUv-9LZJygKHnuDpOLJhlUh_ff41iGDmRIW2ElmO-22mqzuaijy3LgXRcem_4mAH-dy0hSyv1sCkuAZnIIB2PSNuS7GDuwfefzeoP2XjMANyg4vKSmh5k6rEPyypyJfYXPKl3id7QHErOSzHCLMAcbnL-FMOU3nerwVk5tjh6aBjFVZVwrfqFVAnMBlp=w2560-h1380)

**Comment by KevinYang0120** [comment]
Thank you for the prompt reply!  :)
